version: '3.9'

services:
  db:
    image: mysql:8.0.28
    platform: linux/x86_64
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  elixir:
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    env_file: .env.prod
    command: /app/_build/prod/rel/hooked/bin/hooked start
    expose:
      - "8080"

  dash:
    depends_on:
      - db
    build:
      context: ./dash
      dockerfile: Dockerfile
    restart: always
    env_file: .env.prod
    command: npm run start
    expose:
      - "8081"